import type { CeremonyVenue } from "@/lib/types";

export const ceremonyVenues: CeremonyVenue[] = [
  {
    "standesamt_id": "zivilstandskreis-luzern-luzern-lu",
    "standesamt_name": "Zivilstandskreis Luzern",
    "traulokal_name": "Schloss Meggenhorn / Eichenzimmer",
    "adresse": "Meggenhornstrasse 29",
    "ort": "Meggen",
    "kanton": "LU",
    "beschreibung": "Zivile Trauung im Eichenzimmer; Schlossanlage mit Vierwaldstättersee- und Parkkulisse.",
    "ceremonyMonday": null,
    "ceremonyTuesday": null,
    "ceremonyWednesday": null,
    "ceremonyThursday": true,
    "ceremonyFriday": null,
    "ceremonySaturday": null,
    "ceremonySunday": null,
    "eveningCeremonyAvailable": null,
    "maxCeremonyGuests": 20,
    "wheelchairAccessible": null,
    "parkingAvailable": null,
    "outdoorCeremonyAvailable": false,
    "seasonalAvailability": "April-Oktober zusätzliche Donnerstagnachmittage gemäss Stadt Luzern",
    "venueUrl": "https://www.stadtluzern.ch/_rte/information/652819",
    "imageUrl": "",
    "officialConfirmed": true,
    "sourceUrl": "https://www.stadtluzern.ch/_rte/information/652819",
    "sourceType": "Stadt/Zivilstandsamt",
    "beautyStatus": "Top-Schönheit",
    "highlightLevel": 5,
    "tags": [
      "castle",
      "lake",
      "park",
      "nature",
      "premium",
      "historic",
      "schloss",
      "see",
      "natur",
      "historisch",
      "edel",
      "märchenhaft",
      "featured",
      "romantic"
    ],
    "websitePriority": "Hero",
    "remarks": "Offiziell: Stadt Luzern nennt Eichenzimmer im Schloss Meggenhorn als Trauungslokal."
  },
  {
    "standesamt_id": "zivilstandskreis-luzern-luzern-lu",
    "standesamt_name": "Zivilstandskreis Luzern",
    "traulokal_name": "Portraitsaal im Rathaus Luzern",
    "adresse": "Kornmarkt 3",
    "ort": "Luzern",
    "kanton": "LU",
    "beschreibung": "Prunkvoller Portraitsaal im Rathaus inmitten der Luzerner Altstadt; sehr starkes Stadt-/Altstadt-Traulokal.",
    "ceremonyMonday": null,
    "ceremonyTuesday": null,
    "ceremonyWednesday": null,
    "ceremonyThursday": null,
    "ceremonyFriday": true,
    "ceremonySaturday": null,
    "ceremonySunday": null,
    "eveningCeremonyAvailable": null,
    "maxCeremonyGuests": 50,
    "wheelchairAccessible": null,
    "parkingAvailable": null,
    "outdoorCeremonyAvailable": false,
    "seasonalAvailability": "Ganzjährig / jeweils Freitag gemäss Stadt Luzern",
    "venueUrl": "https://www.stadtluzern.ch/dienstleistungeninformation/11905",
    "imageUrl": "",
    "officialConfirmed": true,
    "sourceUrl": "https://www.stadtluzern.ch/dienstleistungeninformation/11905",
    "sourceType": "Stadt/Zivilstandsamt",
    "beautyStatus": "Sehr schön",
    "highlightLevel": 4,
    "tags": [
      "city",
      "old-town",
      "premium",
      "historic",
      "stadt",
      "altstadt",
      "historisch",
      "edel",
      "rathaus",
      "klassisch",
      "featured",
      "romantic"
    ],
    "websitePriority": "Hoch",
    "remarks": "Offiziell: Stadt Luzern nennt Portraitsaal als ziviles Trauungslokal."
  },
  {
    "standesamt_id": "zivilstandsamt-rapperswil-jona-jona-sg",
    "standesamt_name": "Zivilstandsamt Rapperswil-Jona",
    "traulokal_name": "Schloss Rapperswil",
    "adresse": "Lindenhügel",
    "ort": "Rapperswil-Jona",
    "kanton": "SG",
    "beschreibung": "Zivile Trauung im Schloss mit Altstadt- und Zürichsee-Kulisse.",
    "ceremonyMonday": null,
    "ceremonyTuesday": null,
    "ceremonyWednesday": null,
    "ceremonyThursday": null,
    "ceremonyFriday": true,
    "ceremonySaturday": true,
    "ceremonySunday": null,
    "eveningCeremonyAvailable": null,
    "maxCeremonyGuests": null,
    "wheelchairAccessible": null,
    "parkingAvailable": null,
    "outdoorCeremonyAvailable": false,
    "seasonalAvailability": "Gemäss offiziellen Terminen/Verfügbarkeit",
    "venueUrl": "https://www.rapperswil-jona.ch/dienstleistungen/21076",
    "imageUrl": "",
    "officialConfirmed": true,
    "sourceUrl": "https://www.rapperswil-jona.ch/dienstleistungen/21076",
    "sourceType": "Gemeinde/Zivilstandsamt",
    "beautyStatus": "Top-Schönheit",
    "highlightLevel": 5,
    "tags": [
      "castle",
      "lake",
      "city",
      "old-town",
      "premium",
      "historic",
      "schloss",
      "see",
      "altstadt",
      "panorama",
      "historisch",
      "edel",
      "featured",
      "romantic"
    ],
    "websitePriority": "Hero",
    "remarks": "Sehr starkes Hero-Traulokal für die Plattform."
  },
  {
    "standesamt_id": "zivilstandsamt-oberland-west-thun-be",
    "standesamt_name": "Zivilstandsamt Oberland West",
    "traulokal_name": "Schloss Oberhofen",
    "adresse": "Schloss 4",
    "ort": "Oberhofen am Thunersee",
    "kanton": "BE",
    "beschreibung": "Offizielles externes Trauungslokal im Schloss direkt am Thunersee.",
    "ceremonyMonday": null,
    "ceremonyTuesday": null,
    "ceremonyWednesday": null,
    "ceremonyThursday": null,
    "ceremonyFriday": true,
    "ceremonySaturday": null,
    "ceremonySunday": null,
    "eveningCeremonyAvailable": null,
    "maxCeremonyGuests": 50,
    "wheelchairAccessible": null,
    "parkingAvailable": null,
    "outdoorCeremonyAvailable": false,
    "seasonalAvailability": "Gemäss kantonalen Terminen",
    "venueUrl": "https://www.zivilstand.sid.be.ch/de/start/heirat/externe-trauungslokale.html",
    "imageUrl": "",
    "officialConfirmed": true,
    "sourceUrl": "https://www.zivilstand.sid.be.ch/de/start/heirat/trauungslokale-gaeste.html",
    "sourceType": "Kanton/Zivilstandsamt",
    "beautyStatus": "Top-Schönheit",
    "highlightLevel": 5,
    "tags": [
      "castle",
      "lake",
      "mountains",
      "park",
      "nature",
      "premium",
      "historic",
      "schloss",
      "see",
      "berge",
      "historisch",
      "edel",
      "romantisch",
      "featured",
      "romantic"
    ],
    "websitePriority": "Hero",
    "remarks": "Kanton Bern führt es als externes Trauungslokal."
  },
  {
    "standesamt_id": "zivilstandsamt-oberland-west-thun-be",
    "standesamt_name": "Zivilstandsamt Oberland West",
    "traulokal_name": "Schloss Schadau",
    "adresse": "Seestrasse 45",
    "ort": "Thun",
    "kanton": "BE",
    "beschreibung": "Offizielles externes Trauungslokal im Schadaupark am Thunersee.",
    "ceremonyMonday": null,
    "ceremonyTuesday": null,
    "ceremonyWednesday": null,
    "ceremonyThursday": null,
    "ceremonyFriday": true,
    "ceremonySaturday": null,
    "ceremonySunday": null,
    "eveningCeremonyAvailable": null,
    "maxCeremonyGuests": 40,
    "wheelchairAccessible": null,
    "parkingAvailable": null,
    "outdoorCeremonyAvailable": false,
    "seasonalAvailability": "Gemäss kantonalen Terminen",
    "venueUrl": "https://www.zivilstand.sid.be.ch/de/start/heirat/externe-trauungslokale.html",
    "imageUrl": "",
    "officialConfirmed": true,
    "sourceUrl": "https://www.zivilstand.sid.be.ch/de/start/heirat/trauungslokale-gaeste.html",
    "sourceType": "Kanton/Zivilstandsamt",
    "beautyStatus": "Top-Schönheit",
    "highlightLevel": 5,
    "tags": [
      "castle",
      "lake",
      "mountains",
      "city",
      "park",
      "nature",
      "premium",
      "historic",
      "schloss",
      "see",
      "berge",
      "historisch",
      "edel",
      "grandhotel",
      "featured",
      "romantic"
    ],
    "websitePriority": "Hero",
    "remarks": "Kanton Bern führt es als externes Trauungslokal."
  },
  {
    "standesamt_id": "regionales-zivilstandsamt-lenzburg-lenzburg-ag",
    "standesamt_name": "Regionales Zivilstandsamt Lenzburg",
    "traulokal_name": "Schloss Hallwyl",
    "adresse": "Museum Aargau / Schloss Hallwyl",
    "ort": "Seengen",
    "kanton": "AG",
    "beschreibung": "Offizielles Trauungslokal im romantischen Wasserschloss.",
    "ceremonyMonday": null,
    "ceremonyTuesday": null,
    "ceremonyWednesday": null,
    "ceremonyThursday": null,
    "ceremonyFriday": true,
    "ceremonySaturday": null,
    "ceremonySunday": null,
    "eveningCeremonyAvailable": null,
    "maxCeremonyGuests": null,
    "wheelchairAccessible": null,
    "parkingAvailable": null,
    "outdoorCeremonyAvailable": false,
    "seasonalAvailability": "Gemäss Zivilstandsamt Lenzburg",
    "venueUrl": "https://www.lenzburg.ch/trauungslokale/72952",
    "imageUrl": "",
    "officialConfirmed": true,
    "sourceUrl": "https://www.lenzburg.ch/trauungslokale/72952",
    "sourceType": "Gemeinde/Zivilstandsamt",
    "beautyStatus": "Top-Schönheit",
    "highlightLevel": 5,
    "tags": [
      "castle",
      "water-castle",
      "park",
      "nature",
      "premium",
      "historic",
      "wasserschloss",
      "schloss",
      "natur",
      "historisch",
      "romantisch",
      "edel",
      "featured",
      "romantic"
    ],
    "websitePriority": "Hero",
    "remarks": "Sehr starkes Wasserschloss für Filter/SEO."
  },
  {
    "standesamt_id": "regionales-zivilstandsamt-lenzburg-lenzburg-ag",
    "standesamt_name": "Regionales Zivilstandsamt Lenzburg",
    "traulokal_name": "Schloss Lenzburg",
    "adresse": "Schloss",
    "ort": "Lenzburg",
    "kanton": "AG",
    "beschreibung": "Offizielles Trauungslokal auf historischer Schlossanlage oberhalb der Stadt.",
    "ceremonyMonday": null,
    "ceremonyTuesday": null,
    "ceremonyWednesday": null,
    "ceremonyThursday": null,
    "ceremonyFriday": true,
    "ceremonySaturday": null,
    "ceremonySunday": null,
    "eveningCeremonyAvailable": null,
    "maxCeremonyGuests": null,
    "wheelchairAccessible": null,
    "parkingAvailable": null,
    "outdoorCeremonyAvailable": false,
    "seasonalAvailability": "Gemäss Zivilstandsamt Lenzburg",
    "venueUrl": "https://www.lenzburg.ch/trauungslokale",
    "imageUrl": "",
    "officialConfirmed": true,
    "sourceUrl": "https://www.lenzburg.ch/trauungslokale",
    "sourceType": "Gemeinde/Zivilstandsamt",
    "beautyStatus": "Sehr schön",
    "highlightLevel": 4,
    "tags": [
      "castle",
      "city",
      "premium",
      "historic",
      "schloss",
      "historisch",
      "edel",
      "stadt",
      "panorama",
      "featured",
      "romantic"
    ],
    "websitePriority": "Hoch",
    "remarks": "Gutes Schloss-/Aargau-SEO."
  },
  {
    "standesamt_id": "regionales-zivilstandsamt-lenzburg-lenzburg-ag",
    "standesamt_name": "Regionales Zivilstandsamt Lenzburg",
    "traulokal_name": "Schloss Wildegg",
    "adresse": "Museum Aargau / Schloss Wildegg",
    "ort": "Möriken-Wildegg",
    "kanton": "AG",
    "beschreibung": "Offizielles Trauungslokal in historischer Schlossanlage mit Garten.",
    "ceremonyMonday": null,
    "ceremonyTuesday": null,
    "ceremonyWednesday": null,
    "ceremonyThursday": null,
    "ceremonyFriday": true,
    "ceremonySaturday": null,
    "ceremonySunday": null,
    "eveningCeremonyAvailable": null,
    "maxCeremonyGuests": null,
    "wheelchairAccessible": null,
    "parkingAvailable": null,
    "outdoorCeremonyAvailable": false,
    "seasonalAvailability": "Gemäss Zivilstandsamt/Museum Aargau",
    "venueUrl": "https://www.museumaargau.ch/raeume-mieten-und-feiern/detail/ziviltraulokal-eingangshalle",
    "imageUrl": "",
    "officialConfirmed": true,
    "sourceUrl": "https://www.museumaargau.ch/raeume-mieten-und-feiern/detail/ziviltraulokal-eingangshalle",
    "sourceType": "Offizielle Location/Ziviltraulokal",
    "beautyStatus": "Sehr schön",
    "highlightLevel": 4,
    "tags": [
      "castle",
      "park",
      "nature",
      "premium",
      "historic",
      "schloss",
      "garten",
      "natur",
      "historisch",
      "edel",
      "featured",
      "romantic"
    ],
    "websitePriority": "Hoch",
    "remarks": "Als offizielles Ziviltraulokal ausgewiesen."
  },
  {
    "standesamt_id": "zivilstandsamt-zuerich-zuerich-zh",
    "standesamt_name": "Zivilstandsamt Zürich",
    "traulokal_name": "Trauzimmer im Stadthaus Zürich",
    "adresse": "Stadthausquai 17",
    "ort": "Zürich",
    "kanton": "ZH",
    "beschreibung": "Klassisches ziviles Trauzimmer im Stadthaus; sehr stark für urbane/Altstadt-Hochzeiten.",
    "ceremonyMonday": null,
    "ceremonyTuesday": true,
    "ceremonyWednesday": true,
    "ceremonyThursday": true,
    "ceremonyFriday": true,
    "ceremonySaturday": null,
    "ceremonySunday": null,
    "eveningCeremonyAvailable": null,
    "maxCeremonyGuests": null,
    "wheelchairAccessible": true,
    "parkingAvailable": null,
    "outdoorCeremonyAvailable": false,
    "seasonalAvailability": "Ganzjährig",
    "venueUrl": "https://www.stadt-zuerich.ch/de/lebenslagen/einwohner-services/heiraten.html",
    "imageUrl": "",
    "officialConfirmed": true,
    "sourceUrl": "https://www.stadt-zuerich.ch/de/lebenslagen/einwohner-services/heiraten.html",
    "sourceType": "Stadt/Zivilstandsamt",
    "beautyStatus": "Schön",
    "highlightLevel": 3,
    "tags": [
      "city",
      "old-town",
      "premium",
      "historic",
      "stadt",
      "altstadt",
      "historisch",
      "urban",
      "elegant",
      "romantic"
    ],
    "websitePriority": "Mittel",
    "remarks": "Klassische Zürcher Ziviltrauung; nicht so emotional wie externe Top-Locations."
  },
  {
    "standesamt_id": "zivilstandsamt-zuerich-zuerich-zh",
    "standesamt_name": "Zivilstandsamt Zürich",
    "traulokal_name": "Zoo Zürich / Masoala-Halle",
    "adresse": "Zürichbergstrasse 221",
    "ort": "Zürich",
    "kanton": "ZH",
    "beschreibung": "Exotisches offizielles Traulokal der Stadt Zürich im Zoo; einzigartiges Natur-/Indoor-Setting.",
    "ceremonyMonday": null,
    "ceremonyTuesday": null,
    "ceremonyWednesday": null,
    "ceremonyThursday": null,
    "ceremonyFriday": true,
    "ceremonySaturday": null,
    "ceremonySunday": null,
    "eveningCeremonyAvailable": null,
    "maxCeremonyGuests": null,
    "wheelchairAccessible": null,
    "parkingAvailable": true,
    "outdoorCeremonyAvailable": false,
    "seasonalAvailability": "Ganzjährig / gemäss Stadt Zürich",
    "venueUrl": "https://www.stadt-zuerich.ch/misc/de/mitteilungsarchiv/medienmitteilungen/2008/12/081216a.html",
    "imageUrl": "",
    "officialConfirmed": true,
    "sourceUrl": "https://www.stadt-zuerich.ch/misc/de/mitteilungsarchiv/medienmitteilungen/2008/12/081216a.html",
    "sourceType": "Stadt/Zivilstandsamt",
    "beautyStatus": "Top-Schönheit",
    "highlightLevel": 5,
    "tags": [
      "city",
      "nature",
      "premium",
      "unique",
      "exotisch",
      "natur",
      "indoor",
      "modern",
      "einzigartig",
      "stadt",
      "featured",
      "romantic"
    ],
    "websitePriority": "Hero",
    "remarks": "Sehr differenzierendes Highlight; Stadt Zürich nennt den Zoo ausdrücklich als Traulokal."
  },
  {
    "standesamt_id": "zivilstandsamt-zuerich-zuerich-zh",
    "standesamt_name": "Zivilstandsamt Zürich",
    "traulokal_name": "Zunfthaus zur Waag",
    "adresse": "Münsterhof 8",
    "ort": "Zürich",
    "kanton": "ZH",
    "beschreibung": "Offizielles Zürcher Traulokal mit historischem Zunfthaus-Ambiente.",
    "ceremonyMonday": null,
    "ceremonyTuesday": null,
    "ceremonyWednesday": null,
    "ceremonyThursday": null,
    "ceremonyFriday": true,
    "ceremonySaturday": null,
    "ceremonySunday": null,
    "eveningCeremonyAvailable": null,
    "maxCeremonyGuests": 60,
    "wheelchairAccessible": null,
    "parkingAvailable": null,
    "outdoorCeremonyAvailable": false,
    "seasonalAvailability": "Ganzjährig / gemäss Stadt Zürich",
    "venueUrl": "https://www.stadt-zuerich.ch/misc/de/mitteilungsarchiv/medienmitteilungen/2008/12/081216a.html",
    "imageUrl": "",
    "officialConfirmed": true,
    "sourceUrl": "https://www.stadt-zuerich.ch/misc/de/mitteilungsarchiv/medienmitteilungen/2008/12/081216a.html",
    "sourceType": "Stadt/Zivilstandsamt",
    "beautyStatus": "Sehr schön",
    "highlightLevel": 4,
    "tags": [
      "city",
      "old-town",
      "premium",
      "historic",
      "zunfthaus",
      "altstadt",
      "historisch",
      "edel",
      "fine dining",
      "stadt",
      "featured",
      "romantic"
    ],
    "websitePriority": "Hoch",
    "remarks": "Stadt Zürich nennt Zunfthaus zur Waag ausdrücklich als Traulokal."
  },
  {
    "standesamt_id": "zivilstandsamt-zuerich-zuerich-zh",
    "standesamt_name": "Zivilstandsamt Zürich",
    "traulokal_name": "Weinschenke Hotel Hirschen",
    "adresse": "Niederdorfstrasse 13",
    "ort": "Zürich",
    "kanton": "ZH",
    "beschreibung": "Offizielles Zürcher Traulokal im historischen Gewölbekeller.",
    "ceremonyMonday": null,
    "ceremonyTuesday": null,
    "ceremonyWednesday": null,
    "ceremonyThursday": null,
    "ceremonyFriday": true,
    "ceremonySaturday": null,
    "ceremonySunday": null,
    "eveningCeremonyAvailable": null,
    "maxCeremonyGuests": 40,
    "wheelchairAccessible": null,
    "parkingAvailable": null,
    "outdoorCeremonyAvailable": false,
    "seasonalAvailability": "Ganzjährig / gemäss Stadt Zürich",
    "venueUrl": "https://www.stadt-zuerich.ch/misc/de/mitteilungsarchiv/medienmitteilungen/2008/12/081216a.html",
    "imageUrl": "",
    "officialConfirmed": true,
    "sourceUrl": "https://www.stadt-zuerich.ch/misc/de/mitteilungsarchiv/medienmitteilungen/2008/12/081216a.html",
    "sourceType": "Stadt/Zivilstandsamt",
    "beautyStatus": "Schön",
    "highlightLevel": 3,
    "tags": [
      "city",
      "old-town",
      "premium",
      "historic",
      "gewölbekeller",
      "altstadt",
      "historisch",
      "romantisch",
      "intim",
      "stadt",
      "romantic"
    ],
    "websitePriority": "Mittel",
    "remarks": "Speziell/intim; gutes Nischen-Highlight."
  },
  {
    "standesamt_id": "zivilstandskreis-winterthur-winterthur-zh",
    "standesamt_name": "Zivilstandskreis Winterthur",
    "traulokal_name": "Villa Lindengut / Museum Lindengut",
    "adresse": "Römerstrasse 8",
    "ort": "Winterthur",
    "kanton": "ZH",
    "beschreibung": "Historisches Trauzimmer in der Villa Lindengut; traditioneller Winterthurer Trauungsort.",
    "ceremonyMonday": null,
    "ceremonyTuesday": true,
    "ceremonyWednesday": true,
    "ceremonyThursday": true,
    "ceremonyFriday": true,
    "ceremonySaturday": null,
    "ceremonySunday": null,
    "eveningCeremonyAvailable": null,
    "maxCeremonyGuests": 15,
    "wheelchairAccessible": null,
    "parkingAvailable": null,
    "outdoorCeremonyAvailable": false,
    "seasonalAvailability": "Sondertermine / gemäss Stadt Winterthur",
    "venueUrl": "https://stadt.winterthur.ch/gemeinde/verwaltung/sicherheit-und-umwelt/melde-und-zivilstandswesen/zivilstandsamt/heirat/lokale-daten-und-zeiten/museum-lindengut",
    "imageUrl": "",
    "officialConfirmed": true,
    "sourceUrl": "https://stadt.winterthur.ch/gemeinde/verwaltung/sicherheit-und-umwelt/melde-und-zivilstandswesen/zivilstandsamt/heirat/lokale-daten-und-zeiten/museum-lindengut",
    "sourceType": "Stadt/Zivilstandsamt",
    "beautyStatus": "Sehr schön",
    "highlightLevel": 4,
    "tags": [
      "city",
      "park",
      "premium",
      "historic",
      "villa",
      "garten",
      "historisch",
      "stadt",
      "edel",
      "kultur",
      "featured",
      "romantic"
    ],
    "websitePriority": "Hoch",
    "remarks": "Wichtigste schöne Winterthur-Location."
  },
  {
    "standesamt_id": "zivilstandskreis-winterthur-winterthur-zh",
    "standesamt_name": "Zivilstandskreis Winterthur",
    "traulokal_name": "Alte Kaserne Winterthur",
    "adresse": "Technikumstrasse 8",
    "ort": "Winterthur",
    "kanton": "ZH",
    "beschreibung": "Offizielles zusätzliches Traulokal im urbanen Kulturumfeld.",
    "ceremonyMonday": null,
    "ceremonyTuesday": null,
    "ceremonyWednesday": null,
    "ceremonyThursday": null,
    "ceremonyFriday": true,
    "ceremonySaturday": null,
    "ceremonySunday": null,
    "eveningCeremonyAvailable": null,
    "maxCeremonyGuests": null,
    "wheelchairAccessible": null,
    "parkingAvailable": null,
    "outdoorCeremonyAvailable": false,
    "seasonalAvailability": "Gemäss Online-Kalender/Sondertermine",
    "venueUrl": "https://stadt.winterthur.ch/gemeinde/verwaltung/sicherheit-und-umwelt/melde-und-zivilstandswesen/zivilstandsamt/heirat/lokale-daten-und-zeiten",
    "imageUrl": "",
    "officialConfirmed": true,
    "sourceUrl": "https://stadt.winterthur.ch/gemeinde/verwaltung/sicherheit-und-umwelt/melde-und-zivilstandswesen/zivilstandsamt/heirat/lokale-daten-und-zeiten",
    "sourceType": "Stadt/Zivilstandsamt",
    "beautyStatus": "Schön",
    "highlightLevel": 3,
    "tags": [
      "city",
      "historic",
      "stadt",
      "urban",
      "kultur",
      "historisch"
    ],
    "websitePriority": "Mittel",
    "remarks": "Für Grossstadt-/Urban-Filter ergänzend."
  },
  {
    "standesamt_id": "zivilstandskreis-winterthur-winterthur-zh",
    "standesamt_name": "Zivilstandskreis Winterthur",
    "traulokal_name": "Casinotheater Winterthur",
    "adresse": "Stadthausstrasse 119",
    "ort": "Winterthur",
    "kanton": "ZH",
    "beschreibung": "Offizielles zusätzliches Traulokal mit urbanem Kultur-/Theatercharakter.",
    "ceremonyMonday": null,
    "ceremonyTuesday": null,
    "ceremonyWednesday": null,
    "ceremonyThursday": null,
    "ceremonyFriday": true,
    "ceremonySaturday": null,
    "ceremonySunday": null,
    "eveningCeremonyAvailable": null,
    "maxCeremonyGuests": null,
    "wheelchairAccessible": null,
    "parkingAvailable": null,
    "outdoorCeremonyAvailable": false,
    "seasonalAvailability": "Gemäss Online-Kalender/Sondertermine",
    "venueUrl": "https://stadt.winterthur.ch/gemeinde/verwaltung/sicherheit-und-umwelt/melde-und-zivilstandswesen/zivilstandsamt/heirat/lokale-daten-und-zeiten",
    "imageUrl": "",
    "officialConfirmed": true,
    "sourceUrl": "https://stadt.winterthur.ch/gemeinde/verwaltung/sicherheit-und-umwelt/melde-und-zivilstandswesen/zivilstandsamt/heirat/lokale-daten-und-zeiten",
    "sourceType": "Stadt/Zivilstandsamt",
    "beautyStatus": "Schön",
    "highlightLevel": 3,
    "tags": [
      "city",
      "premium",
      "historic",
      "stadt",
      "theater",
      "urban",
      "kultur",
      "edel",
      "romantic"
    ],
    "websitePriority": "Mittel",
    "remarks": "Gutes urbanes Ergänzungsangebot."
  },
  {
    "standesamt_id": "zivilstandsamt-emmental-langnau-im-emmental-be",
    "standesamt_name": "Zivilstandsamt Emmental",
    "traulokal_name": "Schloss Burgdorf",
    "adresse": "Schloss Burgdorf",
    "ort": "Burgdorf",
    "kanton": "BE",
    "beschreibung": "Offizielles externes Trauungslokal im Schloss Burgdorf.",
    "ceremonyMonday": null,
    "ceremonyTuesday": null,
    "ceremonyWednesday": null,
    "ceremonyThursday": null,
    "ceremonyFriday": true,
    "ceremonySaturday": null,
    "ceremonySunday": null,
    "eveningCeremonyAvailable": null,
    "maxCeremonyGuests": 20,
    "wheelchairAccessible": null,
    "parkingAvailable": null,
    "outdoorCeremonyAvailable": false,
    "seasonalAvailability": "Gemäss Kanton Bern",
    "venueUrl": "https://www.zivilstand.sid.be.ch/de/start/heirat/externe-trauungslokale/schloss-burgdorf.html",
    "imageUrl": "",
    "officialConfirmed": true,
    "sourceUrl": "https://www.zivilstand.sid.be.ch/de/start/heirat/externe-trauungslokale/schloss-burgdorf.html",
    "sourceType": "Kanton/Zivilstandsamt",
    "beautyStatus": "Schön",
    "highlightLevel": 3,
    "tags": [
      "castle",
      "city",
      "old-town",
      "historic",
      "schloss",
      "altstadt",
      "historisch",
      "mittelalterlich",
      "stadt"
    ],
    "websitePriority": "Mittel",
    "remarks": "Offiziell bestätigt; als Schloss-/Emmental-Filter wertvoll."
  },
  {
    "standesamt_id": "zivilstandsamt-oberaargau-langenthal-be",
    "standesamt_name": "Zivilstandsamt Oberaargau",
    "traulokal_name": "Schloss Thunstetten / Landvogtstube & Pavillon",
    "adresse": "Berggasse 5",
    "ort": "Thunstetten",
    "kanton": "BE",
    "beschreibung": "Offizielles externes Trauungslokal im barocken Schloss Thunstetten.",
    "ceremonyMonday": null,
    "ceremonyTuesday": null,
    "ceremonyWednesday": null,
    "ceremonyThursday": null,
    "ceremonyFriday": true,
    "ceremonySaturday": null,
    "ceremonySunday": null,
    "eveningCeremonyAvailable": null,
    "maxCeremonyGuests": 21,
    "wheelchairAccessible": null,
    "parkingAvailable": null,
    "outdoorCeremonyAvailable": false,
    "seasonalAvailability": "Gemäss Kanton Bern",
    "venueUrl": "https://www.zivilstand.sid.be.ch/de/start/heirat/externe-trauungslokale/schloss-thunstetten.html",
    "imageUrl": "",
    "officialConfirmed": true,
    "sourceUrl": "https://www.zivilstand.sid.be.ch/de/start/heirat/externe-trauungslokale/schloss-thunstetten.html",
    "sourceType": "Kanton/Zivilstandsamt",
    "beautyStatus": "Schön",
    "highlightLevel": 3,
    "tags": [
      "castle",
      "park",
      "nature",
      "premium",
      "historic",
      "schloss",
      "barock",
      "garten",
      "historisch",
      "edel",
      "romantic"
    ],
    "websitePriority": "Mittel",
    "remarks": "Offiziell bestätigt; Landvogtstube und Pavillon je max. 21 Gäste."
  },
  {
    "standesamt_id": "office-etat-civil-geneve-geneve-ge",
    "standesamt_name": "Service de l'état civil de la Ville de Genève",
    "traulokal_name": "Ancienne mairie des Eaux-Vives / Salle des mariages",
    "adresse": "Rue de la Mairie 37",
    "ort": "Genève",
    "kanton": "GE",
    "beschreibung": "Offizieller Ort für zivile Trauungen der Stadt Genf in der alten Mairie des Eaux-Vives.",
    "ceremonyMonday": true,
    "ceremonyTuesday": true,
    "ceremonyWednesday": true,
    "ceremonyThursday": true,
    "ceremonyFriday": true,
    "ceremonySaturday": null,
    "ceremonySunday": null,
    "eveningCeremonyAvailable": null,
    "maxCeremonyGuests": null,
    "wheelchairAccessible": null,
    "parkingAvailable": null,
    "outdoorCeremonyAvailable": false,
    "seasonalAvailability": "Ganzjährig",
    "venueUrl": "https://www.geneve.ch/demarches/celebration-mariage",
    "imageUrl": "",
    "officialConfirmed": true,
    "sourceUrl": "https://www.geneve.ch/demarches/celebration-mariage",
    "sourceType": "Stadt/Zivilstandsamt",
    "beautyStatus": "Schön",
    "highlightLevel": 3,
    "tags": [
      "city",
      "premium",
      "historic",
      "stadt",
      "historisch",
      "mairie",
      "genf",
      "elegant",
      "romantic"
    ],
    "websitePriority": "Mittel",
    "remarks": "Wichtig für Grossstadt Genf."
  },
  {
    "standesamt_id": "office-etat-civil-geneve-geneve-ge",
    "standesamt_name": "Service de l'état civil de la Ville de Genève",
    "traulokal_name": "Palais Eynard",
    "adresse": "Rue de la Croix-Rouge 4",
    "ort": "Genève",
    "kanton": "GE",
    "beschreibung": "Besonderer städtischer Zeremonieort der Stadt Genf mit Palais-/Park-Ambiente.",
    "ceremonyMonday": null,
    "ceremonyTuesday": null,
    "ceremonyWednesday": null,
    "ceremonyThursday": null,
    "ceremonyFriday": true,
    "ceremonySaturday": null,
    "ceremonySunday": null,
    "eveningCeremonyAvailable": null,
    "maxCeremonyGuests": null,
    "wheelchairAccessible": null,
    "parkingAvailable": null,
    "outdoorCeremonyAvailable": false,
    "seasonalAvailability": "Gemäss Stadt Genf",
    "venueUrl": "https://www.geneve.ch/themes/civil-parcours-vie/marier-convertir-partenariat/lieux-celebration",
    "imageUrl": "",
    "officialConfirmed": true,
    "sourceUrl": "https://www.geneve.ch/themes/civil-parcours-vie/marier-convertir-partenariat/lieux-celebration",
    "sourceType": "Stadt/Zivilstandsamt",
    "beautyStatus": "Sehr schön",
    "highlightLevel": 4,
    "tags": [
      "city",
      "park",
      "premium",
      "historic",
      "palais",
      "stadt",
      "historisch",
      "edel",
      "genf",
      "featured",
      "romantic"
    ],
    "websitePriority": "Hoch",
    "remarks": "Für Luxury-/Palais-Filter interessant."
  },
  {
    "standesamt_id": "office-etat-civil-geneve-geneve-ge",
    "standesamt_name": "Service de l'état civil de la Ville de Genève",
    "traulokal_name": "Hôtel-Restaurant du Parc des Eaux-Vives",
    "adresse": "Quai Gustave-Ador 82",
    "ort": "Genève",
    "kanton": "GE",
    "beschreibung": "Besonderer offizieller Zeremonieort in Park-/See-Nähe.",
    "ceremonyMonday": null,
    "ceremonyTuesday": null,
    "ceremonyWednesday": null,
    "ceremonyThursday": null,
    "ceremonyFriday": true,
    "ceremonySaturday": null,
    "ceremonySunday": null,
    "eveningCeremonyAvailable": null,
    "maxCeremonyGuests": null,
    "wheelchairAccessible": null,
    "parkingAvailable": null,
    "outdoorCeremonyAvailable": false,
    "seasonalAvailability": "Gemäss Stadt Genf",
    "venueUrl": "https://www.geneve.ch/hotel-restaurant-parc-eaux-vives",
    "imageUrl": "",
    "officialConfirmed": true,
    "sourceUrl": "https://www.geneve.ch/hotel-restaurant-parc-eaux-vives",
    "sourceType": "Stadt/Zivilstandsamt",
    "beautyStatus": "Sehr schön",
    "highlightLevel": 4,
    "tags": [
      "lake",
      "city",
      "park",
      "nature",
      "premium",
      "historic",
      "see",
      "villa",
      "hotel",
      "historisch",
      "edel",
      "genf",
      "featured",
      "romantic"
    ],
    "websitePriority": "Hoch",
    "remarks": "Starker Genfer See-/Park-Filter."
  },
  {
    "standesamt_id": "lugano-stato-civile-lugano-ti",
    "standesamt_name": "Ufficio dello stato civile Lugano",
    "traulokal_name": "Palazzo Civico / Sala Matrimoni",
    "adresse": "Piazza della Riforma",
    "ort": "Lugano",
    "kanton": "TI",
    "beschreibung": "Offizielle Sala Matrimoni der Stadt Lugano im Palazzo Civico.",
    "ceremonyMonday": true,
    "ceremonyTuesday": true,
    "ceremonyWednesday": true,
    "ceremonyThursday": true,
    "ceremonyFriday": true,
    "ceremonySaturday": null,
    "ceremonySunday": null,
    "eveningCeremonyAvailable": null,
    "maxCeremonyGuests": null,
    "wheelchairAccessible": null,
    "parkingAvailable": null,
    "outdoorCeremonyAvailable": false,
    "seasonalAvailability": "Ganzjährig",
    "venueUrl": "https://www.lugano.ch/law/17059031/2-5-12-Ordinanza-municipale-sull-uso-delle-sale-per-la-celebrazione-dei-matrimoni-del-23-gennaio-2025",
    "imageUrl": "",
    "officialConfirmed": true,
    "sourceUrl": "https://www.lugano.ch/law/17059031/2-5-12-Ordinanza-municipale-sull-uso-delle-sale-per-la-celebrazione-dei-matrimoni-del-23-gennaio-2025",
    "sourceType": "Stadt/Gemeinde",
    "beautyStatus": "Schön",
    "highlightLevel": 3,
    "tags": [
      "city",
      "premium",
      "historic",
      "stadt",
      "palazzo",
      "historisch",
      "edel",
      "tessin",
      "romantic"
    ],
    "websitePriority": "Mittel",
    "remarks": "Wichtig für Grossstadt/Lugano."
  },
  {
    "standesamt_id": "lugano-stato-civile-lugano-ti",
    "standesamt_name": "Ufficio dello stato civile Lugano",
    "traulokal_name": "Palazzo Tosetti Riva / Castagnola",
    "adresse": "Castagnola",
    "ort": "Lugano",
    "kanton": "TI",
    "beschreibung": "Offizielle restaurierte Sala Matrimoni in Castagnola; Lugano-/See-Nähe.",
    "ceremonyMonday": null,
    "ceremonyTuesday": null,
    "ceremonyWednesday": null,
    "ceremonyThursday": null,
    "ceremonyFriday": true,
    "ceremonySaturday": null,
    "ceremonySunday": null,
    "eveningCeremonyAvailable": null,
    "maxCeremonyGuests": null,
    "wheelchairAccessible": null,
    "parkingAvailable": null,
    "outdoorCeremonyAvailable": false,
    "seasonalAvailability": "Gemäss Stadt Lugano",
    "venueUrl": "https://www.lugano.ch/news/20240624-sale-matrimoni-restaurate/",
    "imageUrl": "",
    "officialConfirmed": true,
    "sourceUrl": "https://www.lugano.ch/news/20240624-sale-matrimoni-restaurate/",
    "sourceType": "Stadt/Gemeinde",
    "beautyStatus": "Sehr schön",
    "highlightLevel": 4,
    "tags": [
      "lake",
      "city",
      "premium",
      "historic",
      "villa",
      "see",
      "palazzo",
      "historisch",
      "edel",
      "tessin",
      "mediterran",
      "featured",
      "romantic"
    ],
    "websitePriority": "Hoch",
    "remarks": "Restaurierte Lugano-Trauungsräume; gutes Tessin-Highlight."
  }
];
